level-name = "overworld"
listen-address = "localhost:25565"
motd = "Not A Minecraft Server"
network-compression-threshold = 256
online-mode = true
enforce-secure-profile = true
max-players = 20
view-distance = 10
